services:
  # Servicio para el backend de Node.js
  backend:
    build:
      context: . # Ruta a la carpeta de tu backend
      dockerfile: Dockerfile
    container_name: medcore-backend
    image: medcore-backend
    ports:
      - "3000:3000" # Mapea el puerto 3000 de tu máquina al puerto del contenedor
    env_file:
      - .env
